stages:
  - verify
  - gen
  - invoke_all
  - export_staging
  - export_production
  - export_production-chn
  - export_production-open

before_script:
  - git submodule update --init --recursive
  - chmod +x tps/tps.sh

.verify_template: &verify_template
  stage: verify
  script:
    - cd "${CI_PROJECT_DIR}/${TASK}"
    - ../tps/tps.sh verify

.gen_template: &gen_template
  stage: gen
  script:
    - cd "${CI_PROJECT_DIR}/${TASK}"
    - ../tps/tps.sh gen
  artifacts:
    paths:
      - ${TASK}/tests/
    expire_in: 1 week
  when: manual
  allow_failure: false

.invoke_all_template: &invoke_all_template
  stage: invoke_all
  script:
    - cd "${CI_PROJECT_DIR}/${TASK}"
    - ../tps/tps.sh invoke-all
  when: manual

.export_staging_template: &export_staging_template
  stage: export_staging
  script:
    - cd "${CI_PROJECT_DIR}/${TASK}"
    - ../tps/tps.sh export CMS -o ${TASK}
    - scp -o StrictHostKeyChecking=no -o ProxyCommand="ssh $CONTROL_STAGING_HOST nc 10.0.0.31 22" $TASK.zip 10.0.0.31:~/cms/
    - ssh -o StrictHostKeyChecking=no -J $CONTROL_STAGING_HOST 10.0.0.31 "cd cms; rm -rf $TASK; unzip $TASK.zip; cmsImportTask -L tps_task $TASK --update"
  environment:
    name: "staging_${TASK}"
    deployment_tier: staging
  only:
    - master
  when: manual

.export_production_template: &export_production_template
  stage: export_production
  script:
    - cd "${CI_PROJECT_DIR}/${TASK}"
    - ../tps/tps.sh export CMS -o ${TASK}
    - scp -o StrictHostKeyChecking=no -o ProxyCommand="ssh $CONTROL_PRODUCTION_HOST nc 10.0.0.31 22" $TASK.zip 10.0.0.31:~/cms/
    - ssh -o StrictHostKeyChecking=no -J $CONTROL_PRODUCTION_HOST 10.0.0.31 "cd cms; rm -rf $TASK; unzip $TASK.zip; cmsImportTask -L tps_task $TASK --update"
  environment:
    name: "production_${TASK}"
    deployment_tier: production
  only:
    - master
  when: manual

.export_production-chn_template: &export_production-chn_template
  stage: export_production-chn
  script:
    - cd "${CI_PROJECT_DIR}/${TASK}"
    - ../tps/tps.sh export CMS -o ${TASK}
    - scp -o StrictHostKeyChecking=no -o ProxyCommand="ssh $CONTROL_PRODUCTION_CHN_HOST nc 10.0.1.31 22" $TASK.zip 10.0.1.31:~/cms/
    - ssh -o StrictHostKeyChecking=no -J $CONTROL_PRODUCTION_CHN_HOST 10.0.1.31 "cd cms; rm -rf $TASK; unzip $TASK.zip; cmsImportTask -L tps_task $TASK --update"
  environment:
    name: "production-chn_${TASK}"
    deployment_tier: production
  only:
    - master
  when: manual

.export_production-open_template: &export_production-open_template
  stage: export_production-open
  script:
    - cd "${CI_PROJECT_DIR}/${TASK}"
    - ../tps/tps.sh export CMS -o ${TASK}
    - scp -o StrictHostKeyChecking=no -o ProxyCommand="ssh $CONTROL_PRODUCTION_OPEN_HOST nc 10.0.0.31 22" $TASK.zip 10.0.0.31:~/cms/
    - ssh -o StrictHostKeyChecking=no -J $CONTROL_PRODUCTION_OPEN_HOST 10.0.0.31 "cd cms; rm -rf $TASK; unzip $TASK.zip; cmsImportTask -L tps_task $TASK --update"
  environment:
    name: "production-open_${TASK}"
    deployment_tier: production
  only:
    - master
  when: manual

aplusb:verify:
  <<: *verify_template
  variables:
    TASK: aplusb

aplusb:gen:
  <<: *gen_template
  needs:
    - aplusb:verify
  variables:
    TASK: aplusb

aplusb:invoke_all:
  <<: *invoke_all_template
  needs:
    - aplusb:gen
  variables:
    TASK: aplusb

aplusb:export_staging:
  <<: *export_staging_template
  needs:
    - aplusb:gen
  variables:
    TASK: aplusb

aplusb:export_production:
  <<: *export_production_template
  needs:
    - aplusb:gen
  variables:
    TASK: aplusb

boxes:verify:
  <<: *verify_template
  variables:
    TASK: boxes

boxes:gen:
  <<: *gen_template
  needs:
    - boxes:verify
  variables:
    TASK: boxes

boxes:invoke_all:
  <<: *invoke_all_template
  needs:
    - boxes:gen
  variables:
    TASK: boxes

boxes:export_staging:
  <<: *export_staging_template
  needs:
    - boxes:gen
  variables:
    TASK: boxes

boxes:export_production:
  <<: *export_production_template
  needs:
    - boxes:gen
  variables:
    TASK: boxes

cards:verify:
  <<: *verify_template
  variables:
    TASK: cards

cards:gen:
  <<: *gen_template
  needs:
    - cards:verify
  variables:
    TASK: cards

cards:invoke_all:
  <<: *invoke_all_template
  needs:
    - cards:gen
  variables:
    TASK: cards

cards:export_staging:
  <<: *export_staging_template
  needs:
    - cards:gen
  variables:
    TASK: cards

cards:export_production:
  <<: *export_production_template
  needs:
    - cards:gen
  variables:
    TASK: cards

defence:verify:
  <<: *verify_template
  variables:
    TASK: defence

defence:gen:
  <<: *gen_template
  needs:
    - defence:verify
  variables:
    TASK: defence

defence:invoke_all:
  <<: *invoke_all_template
  needs:
    - defence:gen
  variables:
    TASK: defence

defence:export_staging:
  <<: *export_staging_template
  needs:
    - defence:gen
  variables:
    TASK: defence

defence:export_production:
  <<: *export_production_template
  needs:
    - defence:gen
  variables:
    TASK: defence

height:verify:
  <<: *verify_template
  variables:
    TASK: height

height:gen:
  <<: *gen_template
  needs:
    - height:verify
  variables:
    TASK: height

height:invoke_all:
  <<: *invoke_all_template
  needs:
    - height:gen
  variables:
    TASK: height

height:export_staging:
  <<: *export_staging_template
  needs:
    - height:gen
  variables:
    TASK: height

height:export_production:
  <<: *export_production_template
  needs:
    - height:gen
  variables:
    TASK: height

hexagon:verify:
  <<: *verify_template
  variables:
    TASK: hexagon

hexagon:gen:
  <<: *gen_template
  needs:
    - hexagon:verify
  variables:
    TASK: hexagon

hexagon:invoke_all:
  <<: *invoke_all_template
  needs:
    - hexagon:gen
  variables:
    TASK: hexagon

hexagon:export_staging:
  <<: *export_staging_template
  needs:
    - hexagon:gen
  variables:
    TASK: hexagon

hexagon:export_production:
  <<: *export_production_template
  needs:
    - hexagon:gen
  variables:
    TASK: hexagon

hexagon:export_production-chn:
  <<: *export_production-chn_template
  needs:
    - hexagon:gen
  variables:
    TASK: hexagon

hexagon:export_production-open:
  <<: *export_production-open_template
  needs:
    - hexagon:gen
  variables:
    TASK: hexagon

hoax:verify:
  <<: *verify_template
  variables:
    TASK: hoax

hoax:gen:
  <<: *gen_template
  needs:
    - hoax:verify
  variables:
    TASK: hoax

hoax:invoke_all:
  <<: *invoke_all_template
  needs:
    - hoax:gen
  variables:
    TASK: hoax

hoax:export_staging:
  <<: *export_staging_template
  needs:
    - hoax:gen
  variables:
    TASK: hoax

hoax:export_production:
  <<: *export_production_template
  needs:
    - hoax:gen
  variables:
    TASK: hoax

jumps:verify:
  <<: *verify_template
  variables:
    TASK: jumps

jumps:gen:
  <<: *gen_template
  needs:
    - jumps:verify
  variables:
    TASK: jumps

jumps:invoke_all:
  <<: *invoke_all_template
  needs:
    - jumps:gen
  variables:
    TASK: jumps

jumps:export_staging:
  <<: *export_staging_template
  needs:
    - jumps:gen
  variables:
    TASK: jumps

jumps:export_production:
  <<: *export_production_template
  needs:
    - jumps:gen
  variables:
    TASK: jumps

jumps:export_production-chn:
  <<: *export_production-chn_template
  needs:
    - jumps:gen
  variables:
    TASK: jumps

jumps:export_production-open:
  <<: *export_production-open_template
  needs:
    - jumps:gen
  variables:
    TASK: jumps

roads:verify:
  <<: *verify_template
  variables:
    TASK: roads

roads:gen:
  <<: *gen_template
  needs:
    - roads:verify
  variables:
    TASK: roads

roads:invoke_all:
  <<: *invoke_all_template
  needs:
    - roads:gen
  variables:
    TASK: roads

roads:export_staging:
  <<: *export_staging_template
  needs:
    - roads:gen
  variables:
    TASK: roads

roads:export_production:
  <<: *export_production_template
  needs:
    - roads:gen
  variables:
    TASK: roads

roads:export_production-chn:
  <<: *export_production-chn_template
  needs:
    - roads:gen
  variables:
    TASK: roads

roads:export_production-open:
  <<: *export_production-open_template
  needs:
    - roads:gen
  variables:
    TASK: roads
